### PR TITLE
Style ci and readme update

### PR DESCRIPTION
**Pull request by Domejko**
- Changed `black` command to check code. If it will find any files that need formatting it will fail CI.
- Added contributing to `README.md` with guidelines to run `black` and `pyright`
- Added `type: ignore` on missing import in `simple_tests.py`

### CODE REVIEW

**Comment by Domejko** [comment]
I see that it's working as intended.

**Comment by alat-rights** [comment]
It seems that under "Files Changed" only formatting changes to `setup.py` are visible.

Did you intend to check in more changes than that?

**Comment by alat-rights** [comment]
The `flaky` import isn't raising problems for me. What's the error that made you `type: ignore` it?

**Comment by alat-rights** [comment]
Do you want to make a separate PR with only the CI and formatting change?

Would probably be able to get that merged in quickly.

**Comment by Domejko** [comment]
I have added ignore on `flaky` because at the moment tests can't be run locally so there is no reason (but only temporary) to install `flaky` and when it's not installed then `pyright` throws an error about it.

Sure I will just remove `README.md` from this PR and put it in separate one.

**Comment by alat-rights** [comment]
I don’t think I understand. Why can’t you run tests locally?

**Comment by Domejko** [comment]
Because there are no local tests written yet, only with live API. Matter that we discussed in #10

**Comment by alat-rights** [comment]
I see.

Sounds like you would like to keep `flaky` out of your dev environment until you're able to run the tests.

I think for future contributors, it'd be good if PyRight catches something that breaks tests rather than not. 

Also since we might have flaky tests that don't depend on Anthropic API in the future, I think it's reasonable for missing flaky to raise a problem.

If your problem with that line is purely local, I'd lean toward not type ignoring that line.

**Comment by alat-rights** [comment]
I rolled back that change for now. We can discuss more if you feel strongly!

**Comment by alat-rights** [comment]
Oh, actually: Is your problem `import-untyped`?

That should hopefully go away if you use the `standard` typing mode on PyRight, which is what I'm using on my end.

**Pull request merged**
